ALTER TABLE DOWNLOAD DROP FOREIGN KEY FK_DOWNLOAD_USER_USERID
ALTER TABLE INVOICE DROP FOREIGN KEY FK_INVOICE_USER_USERID
ALTER TABLE LINEITEM DROP FOREIGN KEY FK_LINEITEM_PRODUCT_PRODUCTID
ALTER TABLE INVOICE_LINEITEM DROP FOREIGN KEY FK_INVOICE_LINEITEM_lineItems_LINEITEMID
ALTER TABLE INVOICE_LINEITEM DROP FOREIGN KEY FK_INVOICE_LINEITEM_Invoice_INVOICENUMBER
DROP TABLE DOWNLOAD
DROP TABLE INVOICE
DROP TABLE LINEITEM
DROP TABLE PRODUCT
DROP TABLE USER
DROP TABLE INVOICE_LINEITEM
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
